### ISSUE TITLE
Daily Job is currently not updating dashboards

### ISSUE THREAD

**Issue by reespozzi** [hmcts/dynatrace-availability-dashboards#195]
### What would you like to change?

There is a bug causing no objects to be returned from the cluster, or seeming this way in code https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=316726&view=logs&j=213773f0-8f16-5fa5-1843-86a27e19467b&t=fc2c2d31-a5aa-5f0d-9170-6d84d0f85ede
```code
Traceback (most recent call last):
  File "/home/vsts/work/1/s/scripts/generate_synthetic_monitors.py", line 144, in <module>
    main()
  File "/home/vsts/work/1/s/scripts/generate_synthetic_monitors.py", line 140, in main
    raise Exception("Cluster returned zero objects")
Exception: Cluster returned zero objects
+ git status
```

**Comment by reespozzi** [comment]
```2023-01-03T07:00:53.8364476Z WARNING: Merged "cft-ithc-00-aks-admin" as current context in /home/vsts/.kube/config
2023-01-03T07:00:53.9557901Z ++ kubectl get ingress --context cft-ithc-00-aks-admin --all-namespaces=true -o 'go-template={{ $length := len .items }} {{ if eq $length 0 }}false{{ end }}'
2023-01-03T07:00:54.5293946Z E0103 07:00:54.528895    1743 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

**Comment by reespozzi** [comment]
Since migration to full flux v2, we lost antecedent for flux deployments. https://github.com/hmcts/dynatrace-availability-dashboards/pull/204 moves this to a different label set by flux.
